require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

platform :ios, '13.0'

require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

target 'IdentityWallet' do
  use_frameworks! #:linkage => :static
  use_expo_modules!
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes'
  )
  #use_flipper!({ 'Flipper' => '0.78.0' })
  #use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.1', 'Flipper-RSocket' => '1.3.1')
  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  # end

  #pod 'react-native-document-scanner', :path => '../node_modules/react-native-document-scanner'
  #pod 'FaceSDK'
  #pod 'Firebase/Analytics'
  #pod 'Firebase', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
  #pod 'Firebase/Messaging', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
  #pod 'GoogleUtilities', :modular_headers => true
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  post_install do |installer|
    react_native_post_install(installer)

    # Workaround `Cycle inside FBReactNativeSpec` error for react-native 0.64
    # Reference: https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-812543933
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings["CODE_SIGNING_ALLOWED"] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.2'
        
      end
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
